project_name: bnk
builds:
  - main: ./ignite/cmd/ignite
    ldflags:
      - -s -w -X github.com/ignite-hq/cli/version.Version={{.Tag}} -X github.com/ignite-hq/cli/version.Date={{.Date}} -X github.com/ignite-hq/cli/version.Head={{.FullCommit}}
    goos:
      - linux
      
    goarch:
      - amd64
      
