// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	"github.com/cosmos/cosmos-sdk/crypto/hd"
	"github.com/cosmos/cosmos-sdk/crypto/keyring"
	cryptotypes "github.com/cosmos/cosmos-sdk/crypto/types"
	"github.com/cosmos/cosmos-sdk/types"
	"github.com/stretchr/testify/mock"
)

// AccountInfo 是 AccountInfo 類型的自動生成的模擬類型
type AccountInfo struct {
	mock.Mock
}

// GetAddress 提供了一個具有給定字段的模擬函數：
func (_m *AccountInfo) GetAddress() types.AccAddress {
	ret := _m.Called()

	var r0 types.AccAddress
	if rf, ok := ret.Get(0).(func() types.AccAddress); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AccAddress)
		}
	}

	return r0
}

// GetAlgo 提供了一個具有給定字段的模擬函數：
func (_m *AccountInfo) GetAlgo() hd.PubKeyType {
	ret := _m.Called()

	var r0 hd.PubKeyType
	if rf, ok := ret.Get(0).(func() hd.PubKeyType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(hd.PubKeyType)
	}

	return r0
}

// GetName 提供了一個具有給定字段的模擬函數：
func (_m *AccountInfo) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPath 提供了一個具有給定字段的模擬函數：
func (_m *AccountInfo) GetPath() (*hd.BIP44Params, error) {
	ret := _m.Called()

	var r0 *hd.BIP44Params
	if rf, ok := ret.Get(0).(func() *hd.BIP44Params); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hd.BIP44Params)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPubKey 提供了一個具有給定字段的模擬函數：
func (_m *AccountInfo) GetPubKey() cryptotypes.PubKey {
	ret := _m.Called()

	var r0 cryptotypes.PubKey
	if rf, ok := ret.Get(0).(func() cryptotypes.PubKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cryptotypes.PubKey)
		}
	}

	return r0
}

// GetType 提供具有給定字段的模擬函數：
func (_m *AccountInfo) GetType() keyring.KeyType {
	ret := _m.Called()

	var r0 keyring.KeyType
	if rf, ok := ret.Get(0).(func() keyring.KeyType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(keyring.KeyType)
	}

	return r0
}

type NewAccountInfoT interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountInfo 創建一個新的 AccountInfo 實例。它還在模擬上註冊了一個測試接口和一個清理函數來斷言模擬期望。
func NewAccountInfo(t NewAccountInfoT) *AccountInfo {
	mock := &AccountInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
